name: Run Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # or your preferred version

    - name: Install dependencies
      run: |
        cd ArQana
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
        pip install pytest qiskit  # add any other deps here

    - name: Run tests
      run: pytest
